### ISSUE TITLE
message_filters/cache.h includes wrong header file

### ISSUE THREAD

**Issue by Peter9606** [bponsler/ros_comm#7]
Below is the error log, seems the right header file should be "rcutils/logging_macros.h"
>==> '. /home/peter/workspace/ros2-porting/build/message_filters/cmake__build.sh && /usr/bin/make -j4 -l4' in '/home/peter/workspace/ros2-porting/build/message_filters'
[ 14%] Built target gtest
[ 28%] Built target message_filters
[ 42%] Built target gtest_main
Scanning dependencies of target message_filters-test_chain
Scanning dependencies of target message_filters-test_subscriber
Scanning dependencies of target message_filters-msg_cache_unittest
Scanning dependencies of target message_filters-test_simple
[ 57%] Building CXX object CMakeFiles/message_filters-test_chain.dir/test/test_chain.cpp.o
[ 57%] Building CXX object CMakeFiles/message_filters-test_simple.dir/test/test_simple.cpp.o
[ 64%] Building CXX object CMakeFiles/message_filters-test_subscriber.dir/test/test_subscriber.cpp.o
[ 71%] Building CXX object CMakeFiles/message_filters-msg_cache_unittest.dir/test/msg_cache_unittest.cpp.o
In file included from /home/peter/workspace/ros2-porting/src/ros_comm/utilities/message_filters/test/msg_cache_unittest.cpp:39:0:
/home/peter/workspace/ros2-porting/src/ros_comm/utilities/message_filters/include/message_filters/cache.h:45:38: fatal error: rcutils/logging_macros.hpp: No such file or directory
compilation terminated.
CMakeFiles/message_filters-msg_cache_unittest.dir/build.make:62: recipe for target 'CMakeFiles/message_filters-msg_cache_unittest.dir/test/msg_cache_unittest.cpp.o' failed
make[2]: *** [CMakeFiles/message_filters-msg_cache_unittest.dir/test/msg_cache_unittest.cpp.o] Error 1
CMakeFiles/Makefile2:108: recipe for target 'CMakeFiles/message_filters-msg_cache_unittest.dir/all' failed
make[1]: *** [CMakeFiles/message_filters-msg_cache_unittest.dir/all] Error 2

**Comment by bponsler** [comment]
Closing this since you fixed it
